const express = require("express")
const mongoose = require("mongoose")
const db = require("./backend/config/db")
const cors = require("../../backend/node-express/node_modules/cors")
const app = express()
const controller = require("./backend/controllers/controllers")
app.use(cors())
app.use(express.urlencoded({ extended: true }))
app.use(express.json())
db.connect()
app.post("/login", controller.login)
app.post("/register", controller.register)
app.post("/create-post", controller.createPost)
app.get("/get-all-posts", controller.getAllPosts)
app.listen(process.env.PORT || 5000, () => console.log("app is running"))
process.on("SIGTERM", () => {
  debug("SIGTERM signal received: closing HTTP server")
  server.close(() => {
    debug("HTTP server closed")
  })
})
